### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by GraphicsEnthusiast** [NVIDIA/OptiX_Apps#12]
C:\Users\17199\Desktop\OptiX_Apps-master\OptiX_Apps-master\build>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30145.0
-- The CXX compiler identification is MSVC 19.29.30145.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
LOCAL_3RDPARTY = C:/Users/17199/Desktop/OptiX_Apps-master/OptiX_Apps-master/3rdparty
CMAKE_MODULE_PATH = C:/Users/17199/Desktop/OptiX_Apps-master/OptiX_Apps-master/3rdparty/CMake
-- Could NOT find OptiX70 (missing: OPTIX70_INCLUDE_DIR)
-- Could NOT find OptiX71 (missing: OPTIX71_INCLUDE_DIR)
-- Could NOT find OptiX72 (missing: OPTIX72_INCLUDE_DIR)
-- Could NOT find OptiX73 (missing: OPTIX73_INCLUDE_DIR)
-- Could NOT find OptiX74 (missing: OPTIX74_INCLUDE_DIR)
-- Found OptiX75: C:/ProgramData/NVIDIA Corporation/OptiX SDK 7.5.0/include

PROJECT_NAME = intro_runtime
-- Found OpenGL: opengl32
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GLFW (missing: GLFW_INCLUDE_DIR GLFW_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  3rdparty/CMake/FindGLFW.cmake:47 (find_package_handle_standard_args)
  apps/intro_runtime/CMakeLists.txt:35 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/17199/Desktop/OptiX_Apps-master/OptiX_Apps-master/build/CMakeFiles/CMakeOutput.log"

**Comment by droettger** [comment]
>Could NOT find GLFW (missing: GLFW_INCLUDE_DIR GLFW_LIBRARIES)

Did you follow the **Building** chapter inside the README.md exactly?
In your development environment using MSVS 2019, running the 3rdparty.cmd script inside the **x64 Native Tools Command Prompt for VS2019** is strictly required once before building the examples. 
That will download, extract, and rename the GLFW libraries into the 3rdparty/glfw folder.

Are you on top of tree of the repository?
I changed the GLFW version from 3.3.2 to 3.3.8 when adding support for MSVS 2022 yesterday because that contains the necessary lib-vc2022 folder.
I used MSVS 2019 when adding support for OptiX SDK 7.5.0 one commit earlier and the GLFW folder structure hasn't changed for that.
